### ISSUE TITLE
Error and crash after hotreload with disabled USharpMinHotReload 

### ISSUE THREAD

**Issue by DmitriySalnikov** [pixeltris/USharp#110]
An error appears immediately after compiling the project when the engine is open.
And then if you try to play/stop the game or if you close the editor crash occurs
but at the same time the library is updated.

```
USharp: Error: Entry point exception (UnrealEngine.Runtime): System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at UnrealEngine.Runtime.ManagedUnrealTypes.BuildTypes() in C:\My\UE_4.23\Engine\Plugins\USharp\Managed\UnrealEngine.Runtime\UnrealEngine.Runtime\Internal\ManagedUnrealTypes.Builder.cs:line 936
   at UnrealEngine.Runtime.ManagedUnrealTypes.Load() in C:\My\UE_4.23\Engine\Plugins\USharp\Managed\UnrealEngine.Runtime\UnrealEngine.Runtime\Internal\ManagedUnrealTypes.Builder.cs:line 72
   at UnrealEngine.Runtime.Native.NativeFunctions.OnNativeFunctionsRegistered() in C:\My\UE_4.23\Engine\Plugins\USharp\Managed\UnrealEngine.Runtime\UnrealEngine.Runtime\Internal\Native\NativeFunctions.cs:line 236
   at UnrealEngine.Runtime.Native.NativeFunctions.RegisterFunctions(IntPtr registerFunctionsAddr) in C:\My\UE_4.23\Engine\Plugins\USharp\Managed\UnrealEngine.Runtime\UnrealEngine.Runtime\Internal\Native\NativeFunctions.cs:line 120
   at UnrealEngine.EntryPoint.DllMain(String arg) in C:\My\UE_4.23\Engine\Plugins\USharp\Managed\UnrealEngine.Runtime\UnrealEngine.Runtime\Internal\EntryPoint.cs:line 80
```

This happen with USharpMinHotReload is disabled and when i add new classes with enabled USharpMinHotReload. May be that's not all conditions.

**Comment by a3st** [comment]
Same problem. Plugin is very unstable. I'd recommend going with native
